# Common configuration.
AllCops:
  # Include common Ruby source files.
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'backup/**/*'
    - 'bundler_stubs/**/*'
    - 'node_modules/**/*'
    - 'log/**/*'
    - '.bundle/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'temp/**/*'
    - 'db/schema.rb'
    - 'Gemfile.lock'

Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
